### ISSUE TITLE
[Bug]: MissingPointerError: Token "components" does not exist

### ISSUE THREAD

**Issue by deckchairlabs** [stepci/stepci#241]
### What happened?

When trying to reference reusable components from a workflow being included via `$ref` this error is thrown.

### What did you expect to happen?

I would expect to be able to reference reusable components just like using `${{env.something}}`

### Version

2.8.2

### Environment

Node v22.6.0

### How can we reproduce this bug?

Create a workflow file that defines some components and attempt to use them in a referenced file.

`workflow.yml`

```yml
version: '1.1'
name: Test
components:
  credentials:
    example:
      basic:
        username: test
        password: test

tests:
  basicAuth:
    $ref: "./basicAuth.yml"
```

`basicAuth.yml`

```yml
steps:
  - name: Basic auth
    http:
      url: /
      method: GET
      auth:
        $ref: '#/components/credentials/example'
```

### Relevant log output

```shell
/workspace/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.1.0/node_modules/@apidevtools/json-schema-ref-parser/lib/pointer.js:94
      throw new MissingPointerError(token, decodeURI(this.originalPath));
            ^

MissingPointerError: Token "components" does not exist.
    at Pointer.resolve (/workspace/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.1.0/node_modules/@apidevtools/json-schema-ref-parser/lib/pointer.js:94:13)
    at $Ref.resolve (/workspace/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.1.0/node_modules/@apidevtools/json-schema-ref-parser/lib/ref.js:124:20)
    at $Refs._resolve (/workspace/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.1.0/node_modules/@apidevtools/json-schema-ref-parser/lib/refs.js:156:15)
    at dereference$Ref (/workspace/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.1.0/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:140:23)
    at crawl (/workspace/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.1.0/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:69:28)
    at crawl (/workspace/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.1.0/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:78:30)
    at crawl (/workspace/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.1.0/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:78:30)
    at crawl (/workspace/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.1.0/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:78:30)
    at dereference$Ref (/workspace/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.1.0/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:160:24)
    at crawl (/workspace/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.1.0/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:69:28) {
  code: 'EMISSINGPOINTER',
  source: '/workspace/api/test/matterTypes.yml',
  path: null,
  toJSON: [Function: toJSON],
  [Symbol(nodejs.util.inspect.custom)]: [Function: inspect]
}
```

### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me

**Comment by deckchairlabs** [comment]
I can confirm the components are accessible if moved within the `basicAuth.yml` file.

**Comment by deckchairlabs** [comment]
Ah, I've just realised I need to reference the document defining the components within the $ref. I'll be closing this! https://swagger.io/docs/specification/using-ref/
