### ISSUE TITLE
[Bug]: generate: Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by mmahut** [stepci/stepci#96]
### What happened?

`stepci generate` errors with

```
$ stepci generate ./openapi.yaml ./workflow.yml
stepci generate [spec] [path]

generate workflow from OpenAPI spec

Positionals:
  spec                    openapi file url    [string] [default: "openapi.json"]
  path                    output file path  [string] [default: "./workflow.yml"]
  generatePathParams                                   [boolean] [default: true]
  generateOptionalParams                               [boolean] [default: true]
  generateRequestBody                                  [boolean] [default: true]
  useExampleValues                                     [boolean] [default: true]
  useDefaultValues                                     [boolean] [default: true]
  checkStatus                                          [boolean] [default: true]
  checkExamples                                        [boolean] [default: true]
  checkSchema                                          [boolean] [default: true]
  contentType                             [string] [default: "application/json"]

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

TypeError: Cannot read properties of undefined (reading 'forEach')
    at generateWorkflow (blockfrost-stepci/node_modules/@stepci/plugin-openapi/index.js:186:42)
    at async generateWorkflowFile (node_modules/@stepci/plugin-openapi/index.js:197:45)
    at async Object.handler (node_modules/stepci/dist/index.js:137:5)
```

### What did you expect to happen?

To get a nice workflow :)

### Version

2.6.2

### Environment

v16.16.0

### How can we reproduce this bug?

Take [this open api file](https://github.com/blockfrost/openapi/blob/master/openapi.yaml) and try it.

### Relevant log output

```shell
TypeError: Cannot read properties of undefined (reading 'forEach')
    at generateWorkflow (/home/mmahut/repo/Blockfrost/blockfrost-stepci/node_modules/@stepci/plugin-openapi/index.js:186:42)
    at async generateWorkflowFile (/home/mmahut/repo/Blockfrost/blockfrost-stepci/node_modules/@stepci/plugin-openapi/index.js:197:45)
    at async Object.handler (/home/mmahut/repo/Blockfrost/blockfrost-stepci/node_modules/stepci/dist/index.js:137:5)
```
```


### Would you be interested in working on a bugfix for this issue?

- [ ] Yes! Assign me

**Comment by mishushakov** [comment]
Thanks for opening the issue! I will take a look at the linked file and see what's wrong 😄

**Comment by mcred** [comment]
Is there any work around for this? I'm having the same issue as well and it's a barrier to getting started with StepCI

**Comment by mishushakov** [comment]
Hey, unfortunately, this is not our priority in the coming two weeks, but i keep the issue in mind
You could help me find the cause for the issue, if you provide a OpenAPI file, where you see the issue occur

😉
